<?php
define('SHOW_VOTING_NAVIGATION', 'SHOW_VOTING_NAVIGATION');
define('HIDE_VOTING_NAVIGATION', 'HIDE_VOTING_NAVIGATION');
define('VOTING_ENABLED', '1');
define('VOTING_AMOUNT', 'VOTING_AMOUNT');
define('ERROR_TYPE_VOTING_NOT_STARTED', 1);
define('ERROR_TYPE_UNAUTHORIZED', 0);
define('CONSTANTS_ACCESS_TOKEN', '88343a4758ad5bd50971e643e2f2b7de');
define('PAY_FOR_LIKES_ENABLED', '1');
define('PAY_FOR_LIKES', 'PAY_FOR_LIKES');
define('LIKE_AMOUNT', 'LIKE_AMOUNT');
