<div style='padding:20px'>
    <p>Voting Terms and Conditions</p>
<p>Exclusively online audience voting has been set-up on behalf of CampOut Nigeria Limited to enable ShufflesTV.com and its affiliate channels/websites online viewers to vote for their favourite contestants in any competition that may be organized by CampOut Nigeria Ltd.&nbsp;</p>
<p>Except otherwise communicated, voting will be via the ShufflesTv in App and Website webpay transactions by use of 3rd Party financial services provider.&nbsp;</p>
<p>No refunds will be offered at any time.&nbsp;</p>
<p>Contestants with the least votes will be eliminated from the competitions as may be determined according to the rules guiding the competition.&nbsp;</p>
<p>Contestant with the total most votes at end of the competition period wins the Star Prize Money.&nbsp;</p>
<p>Votes must be cast between Sundays 7:00pm and Saturdays 12noon during the competition for it to count.</p>
<p><strong>Votes made or received outside of these times will not be factored into the elimination contest for that week but will continue to count for any contestant remaining in the competition.</strong></p>
<p><strong>CampOut Nigeria Ltd reserves the right to change these voting rules at any time, and may suspend, withdraw or re-set voting at its sole discretion.&nbsp;</strong></p>
<p><strong>CampOut Nigeria Ltd</strong> reserves the right to disqualify votes if it has reasonable grounds to suspect that fraudulent voting has occurred or if it considers that there has been any attempt to manipulate the voting fraudulently. It is your responsibility to ensure that any information which you provide to us is accurate, complete and up to date.</p>
<p><strong>CampOut Nigeria Ltd</strong>, THE PRODUCERS OF &ldquo;CAMPOUT9JA&rdquo; (and all other Competitions that may be hosted on ShufflesTV.com and its affiliate Channels/Websites) INCLUDING THEIR HOLDING AND SUBSIDIARY COMPANIES, EMPLOYEES, DIRECTORS, AGENTS, SPONSORS AND SUB-CONTRACTORS (&ldquo;<strong>THE INDEMNIFIED PERSONS</strong>&rdquo;) DO NOT ACCEPT ANY RESPONSIBILITY WHATSOEVER FOR ANY TECHNICAL FAILURE OR MALFUNCTION OR ANY OTHER PROBLEM WITH ANY 3RD PARTY ONLINE FINANCIAL SERVICES PROVIDER, MOBILE NETWORK, SYSTEM, SERVER, PROVIDER, SOFTWARE OR OTHERWISE WHICH MAY RESULT IN ANY VOTE BEING LOST OR NOT PROPERLY RECEIVED, REGISTERED OR RECORDED OR NOT BEING RECEIVED ON OR BEFORE THE CLOSING TIME OF THE RELEVANT VOTING PERIODS.</p>
<p><strong>CampOut Nigeria Ltd</strong> IS COMMITTED TO A FAIR VIEWER VOTING SYSTEM AND TO PREVENTING ABUSE OF ITS SYSTEMS, AS WELL AS THOSE OF ITS AGENTS AND SUB-CONTRACTORS. HOWEVER, <strong>CampOut Nigeria Ltd</strong> DOES NOT GUARANTEE THAT THE ONLINE PAYMENT GATEWAY OR OTHER SYSTEMS USED IN THE VOTING WILL BE FREE FROM ERRORS OR OMISSIONS NOR THAT THEY WILL BE AVAILABLE, UNINTERRUPTED AND IN A FULLY OPERATING CONDITION. IN THE CASE OF SYSTEM FAILURE OR REPAIR OR FOR REASONS BEYOND THE REASONABLE CONTROL OF CAMPOUT9JA, THE SYSTEM AND/OR VOTING SERVICE MAY BE SUSPENDED TEMPORARILY AND WITHOUT NOTICE. THE INDEMNIFIED PERSONS WILL NOT BE LIABLE TO ANY PERSON IN THE EVENT THAT ALL OR ANY PART OF THE SYSTEM AND/OR VOTING SERVICE IS DISCONTINUED, MODIFIED OR INTERRUPTED IN ANY WAY.</p>
<p>YOU HEREBY RELEASE AND/OR INDEMNIFY THE INDEMNIFIED PERSONS FROM ALL LIABILITY (INCLUDING NEGLIGENCE), FOR ANY PERSONAL INJURY, OR DEATH; OR ANY LOSS OR DAMAGE (INCLUDING LOSS OF OPPORTUNITY); WHETHER DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL, ARISING IN ANY WAY OUT OF OR IN CONNECTION WITH YOUR PARTICIPATION IN THE CAMPOUT9JA COMPETITION AND VOTING IN TERMS HEREOF, INCLUDING, BUT NOT LIMITED TO, WHERE ARISING OUT OF THE FOLLOWING: (A) ANY TECHNICAL DIFFICULTIES OR EQUIPMENT MALFUNCTION; (B) ANY THEFT, UNAUTHORISED ACCESS OR THIRD PARTY INTERFERENCE; (C) ANY ENTRY OR PRIZE CLAIM THAT IS LATE, LOST, ALTERED, DAMAGED OR MISDIRECTED DUE TO ANY REASON BEYOND THE REASONABLE CONTROL OF CAMPOUT9JA; (D) ANY VARIATION IN PRIZE VALUE TO THAT STATED IN THESE TERMS AND CONDITIONS; (E) ANY TAX LIABILITY INCURRED BY A WINNER OR ENTRANT; OR (F) USE OF THE PRIZE.</p>
<p><strong>CampOut Nigeria Ltd</strong> will not have a say in the final outcome of the vote. In the event that the vote outcome cannot be reasonably determined (due to a technical failure or other circumstance beyond <strong>CampOut Nigeria Ltd</strong> reasonable control and the data is irrecoverable), then <strong>CampOut Nigeria Ltd</strong> reserves the right to use its discretion to make any decision that is necessary under the circumstances to ensure fairness to all affected parties or postpone the result show or exclude the results from the system that failed, unless the data can be recovered.</p>
<p><strong>CAMPOUT NIGERIA LTD RESERVES THE RIGHT TO AMEND THESE VOTING TERMS AND CONDITIONS WITHOUT PRIOR NOTICE.&nbsp;</strong></p>
<p><br /><br /></p>
</div>